### ISSUE TITLE
Requests sent to Google Spreadsheet

### ISSUE THREAD

**Issue by scmilburn** [SandboxUMD/sandboxUMD.github.io#5]
Requests form should redirect to Google Form/Spreadsheet via HTTP POST to make easier to view. Currently sending to my email (which is bad).

**Comment by Defaultio** [comment]
Here's the tutorial I used to figure this out. Sorry it's just screenshots; it's on a private forum:
http://m.imgur.com/P6iYDrD,Y3mtETx,YM7Eozx,cqKU3Wy,6AWoKW7,Gtv2wnQ

**Comment by progluan** [comment]
moved email to sandboxUMD@gmail.com
